# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./

# Install dependencies without running pre/post scripts
RUN npm install --ignore-scripts

# Copy the rest of the application
COPY . .

# Build the TypeScript project
RUN npm run build

# Expose any necessary ports (if applicable) and set environment variables if needed

# Start the MCP server
CMD ["node", "build/index.js"]
